name: dialect_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies: 
  build_runner: ^2.1.11
  crypto: ^3.0.2
  cryptography: ^2.0.5
  http: ^0.13.4
  json_serializable: ^6.2.0
  pinenacl: ^0.3.4
  shared_preferences: ^0.5.5
  solana: ^0.24.0+1
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
